name: Python CI

on:
  push: {}
  pull_request:
    branches: [ Li ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["anaconda3"]
        os: [macos-latest, windows-latest]
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v --cov=tinydb

    - name: Perform type check
      run: |
        pip install pytest-mypy
        pytest --mypy -m mypy tinydb tests

    - name: Verify dist package format
      if: ${{ matrix.python-version == '3.12' }}
      run: |
        poetry build
        twine check dist/*

    - name: Upload coverage result
      if: ${{ matrix.os != 'windows-latest' }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
         coveralls
