name: Python CI

on:
  push: {}
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        poetry run pytest -v --cov=tinydb

    - name: Perform type check
      run: |
        poetry run pip install pytest-mypy
        poetry run pytest --mypy -m mypy tinydb tests

    - name: Verify dist package format
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        poetry build
        twine check dist/*

    - name: Upload coverage result
      if: ${{ matrix.os != 'windows-latest' }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
         poetry run coveralls
